export const facturesAll = {
  0: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 3655.54,
      tax: false,
      type: "dab",
    },

    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 2978.3,
      tax: true,
      type: "mpt",
    },
  ],
  1: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 3655.54,
      tax: false,
      type: "dab",
    },

    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 2978.3,
      tax: true,
      type: "mpt",
    },
  ],
  2: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 123456,
      tax: false,
      type: "dab",
    },
    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 99999,
      tax: true,
      type: "dab",
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
};
