export const machineriesAll = {
  1: [
    {
      id: 0,
      code: "Caterpillar",
      desc: "Big machine",
      maintenance: 10,
      site_conc: "Madrid",
      hrs_fonc: 99,
      hrs_stat: 12,
      cout: 11390,
      taux_fonc: 12,
      type: "dab",
    },
    {
      id: 1,
      code: "Caterpillar 2",
      desc: "Big machine 2",
      maintenance: 15,
      site_conc: "Madrid",
      hrs_fonc: 40,
      hrs_stat: 33,
      cout: 1240,
      taux_fonc: 21,
      type: "mpt",
    },
  ],
  2: [
    {
      id: 0,
      code: "Hitachi",
      desc: "Big machine",
      maintenance: 2,
      site_conc: "Madrid",
      hrs_fonc: 4,
      hrs_stat: 11,
      cout: 123,
      taux_fonc: 33,
      type: "mi",
    },
    {
      id: 1,
      code: "Hitachi 2",
      desc: "Big machine 2",
      maintenance: 0,
      site_conc: "Madrid",
      hrs_fonc: 22,
      hrs_stat: 67,
      cout: 220000,
      taux_fonc: 88,
      type: "dab",
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
};
