export const machineriesAll = {
  1: [
    {
      id: "Caterpillar",
      desc: "Big machine",
      maintenance: 10,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
      type: "dab",
    },
    {
      id: "Caterpillar 2",
      desc: "Big machine 2",
      maintenance: 15,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
      type: "mpt",
    },
  ],
  2: [
    {
      id: "Hitachi",
      desc: "Big machine",
      maintenance: 2,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
      type: "mi",
    },
    {
      id: "Hitachi 2",
      desc: "Big machine 2",
      maintenance: 0,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
      type: "dab",
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
};
