export const dossierAll = [
  {
    id: "2021MU01",
    Evenement: "Revision of Nonaut Sub in L Low Femur, Open Approach",
    datEv: "2022-03-20",
    status: "actif",
    Admisibilité: false,
    MR: 6633.84,
    MA: 6633.84,
    MV: 4151.93,
    Participation: 6633.84,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-03-24",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU02",
    Evenement: "Replacement of L Atrium with Nonaut Sub, Perc Endo Approach",
    datEv: "2021-09-30",
    status: "fermé",
    Admisibilité: true,
    MR: 31553.84,
    MA: 16686.68,
    MV: 12261.95,
    Participation: 30000.0,
    dab: true,
    mi: true,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU03",
    Evenement: "Repair Pelvis Lymphatic, Percutaneous Approach",
    datEv: "2021-10-17",
    status: "actif",
    Admisibilité: true,
    MR: 455868.0,
    MA: 21609.78,
    MV: 19999.56,
    Participation: 30000.0,
    dab: true,
    mi: true,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU04",
    Evenement: "Restrict of L Parotid Duct with Intralum Dev, Perc Approach",
    datEv: "2021-03-03",
    status: "actif",
    Admisibilité: false,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU05",
    Evenement: "Dilate L Subclav Art, Bifurc, w 2 Drug-elut, Perc",
    datEv: "2021-04-23",
    status: "fermé",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU06",
    Evenement: "Occlusion of Descending Colon, Perc Endo Approach",
    datEv: "3/21/2021",
    status: "actif",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU07",
    Evenement: "Extirpation of Matter from Pons, Open Approach",
    datEv: "2021-07-07",
    status: "actif",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU08",
    Evenement: "Supplement Left Vocal Cord with Nonaut Sub, Endo",
    datEv: "2021-08-28",
    status: "actif",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 7.33,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU09",
    Evenement: "High Dose Rate (HDR) Brachytherapy of Chest using Iodine 125",
    datEv: "2021-09-28",
    status: "fermé",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
  {
    id: "2021MU10",
    Evenement: "Resection of Right Large Intestine, Endo",
    datEv: "2021-10-03",
    status: "fermé",
    Admisibilité: true,
    MR: 0,
    MA: 0,
    MV: 0,
    Participation: 0,
    dab: true,
    mi: false,
    mpt: true,
    bcg: false,
    datOuv: "2022-01-01",
    actOf: "Acte officiel",
    prgm: "Programme",
  },
];

export const facturesAll = {
  0: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Site 1",
      montant_rec: 3655.54,
      tax: false,
      type: "dab",
    },

    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Site 2",
      montant_rec: 2978.3,
      tax: true,
      type: "mpt",
    },
  ],
  1: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Site 2",
      montant_rec: 3655.54,
      tax: false,
      type: "dab",
    },

    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Site 2",
      montant_rec: 2978.3,
      tax: true,
      type: "mpt",
    },
  ],
  2: [
    {
      id: 0,
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Site 16",
      montant_rec: 123456,
      tax: false,
      type: "dab",
    },
    {
      id: 1,
      desc_fact: "Facture 2",
      date_fact: "2021-10-30",
      site_con: "Site 16",
      montant_rec: 99999,
      tax: true,
      type: "dab",
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
};

export const infosMuni = {
  nom: "Quebec",
  adress: "10 Rue Pierre-Olivier-Chauveau",
  ville: "Quebec",
  code_pos: "23027",
  mrc: "-------",
  region: "Centre",
  rfu: "-------",
  contact: "+1 418-651-9890",
  fct: "-------",
  num_telph: "+1 418-651-9890",
  num_telcop: "+1 418-651-9890",
  adress_cour: "10 Rue Pierre-Olivier-Chauveau",
  taux_csst: 2.5,
  taux_ae: "-------",
};
