export const sitesAll = {
  "2021MU01": [
    {
      id: 0,
      site: "Site 1",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 22,
      type_ret: "type",
      adm: true,
      pourc_adm: 80,
      montant_rec: 3655.54,
      f_montant_rec: 3655.54,
      s_montant_rec: 0,
      m_montant_rec: 0,
    },
    {
      id: 1,
      site: "Site 2",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 26,
      type_ret: "type",
      adm: true,
      pourc_adm: 100,
      montant_rec: 0,
      f_montant_rec: 0,
      s_montant_rec: 0,
      m_montant_rec: 0,
    },
  ],
  "2021MU02": [
    {
      id: 0,
      site: "Site 1",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 22,
      type_ret: "type",
      adm: true,
      pourc_adm: 80,
      montant_rec: 24875.54,
      f_montant_rec: 3655.54,
      s_montant_rec: 9830,
      m_montant_rec: 11390,
    },
    {
      id: 1,
      site: "Site 16",
      nature: "sinistre",
      part_end: "ABCD",
      pourc_end: 87,
      type_ret: "type",
      adm: true,
      pourc_adm: 65,
      montant_rec: 3700,
      f_montant_rec: 0,
      s_montant_rec: 2460,
      m_montant_rec: 1240,
    },
  ],
  "2021MU03": [
    {
      id: 0,
      site: "Site 5",
      nature: "sinistre",
      part_end: "ABB",
      pourc_end: 12,
      type_ret: "type",
      adm: true,
      pourc_adm: 90,
      montant_rec: 0,
      f_montant_rec: 0,
      s_montant_rec: 0,
      m_montant_rec: 0,
    },
    {
      id: 1,
      site: "Site 16",
      nature: "sinistre",
      part_end: "DDA",
      pourc_end: 20,
      type_ret: "type",
      adm: true,
      pourc_adm: 11,
      montant_rec: 223455,
      f_montant_rec: 223455,
      s_montant_rec: 0,
      m_montant_rec: 0,
    },
  ],
  "2021MU04": [],
  "2021MU05": [],
  "2021MU06": [],
  "2021MU07": [],
  "2021MU08": [],
  "2021MU09": [],
  "2021MU10": [],
};

export const sitesList = {
  "Site 1": "Site 1",
  "Site 2": "Site 2",
  "Site 3": "Site 3",
  "Site 4": "Site 4",
  "Site 5": "Site 5",
  "Site 6": "Site 6",
  "Site 7": "Site 7",
  "Site 16": "Site 16",
};
