export const sitesAll = {
  "2021MU01": [
    {
      id: 0,
      site: "Site 1",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 22,
      type_ret: "type",
      adm: true,
      pourc_adm: 80,
      montant_rec: 1230,
    },
    {
      id: 1,
      site: "Site 2",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 26,
      type_ret: "type",
      adm: true,
      pourc_adm: 100,
      montant_rec: 2330,
    },
  ],
  "2021MU02": [
    {
      id: 0,
      site: "Site 1",
      nature: "sinistre",
      part_end: "ABC",
      pourc_end: 22,
      type_ret: "type",
      adm: true,
      pourc_adm: 80,
      montant_rec: 1230,
    },
    {
      id: 1,
      site: "Site 16",
      nature: "sinistre",
      part_end: "ABCD",
      pourc_end: 87,
      type_ret: "type",
      adm: true,
      pourc_adm: 65,
      montant_rec: 22890,
    },
  ],
  "2021MU03": [],
  "2021MU04": [],
  "2021MU05": [],
  "2021MU06": [],
  "2021MU07": [],
  "2021MU08": [],
  "2021MU09": [],
  "2021MU10": [],
};
