export const salairesDABData = {
  1: [
    {
      id: 1,
      name: "Aimarah Oussama",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 2460,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "Karim",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 9830,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: false,
      fss: true,
      csst: false,
    },
  ],
  2: [
    {
      id: 1,
      name: "Said 2",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 2460,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "Karim 2",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 9830,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const salairesMPTData = {
  1: [
    {
      id: 1,
      name: "Mstapha",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 9914,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "3li",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 1120,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
    },
  ],
  2: [
    {
      id: 1,
      name: "John Doe",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 25630,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "Hans Landa",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 78346.22,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const salairesMIData = {
  1: [
    {
      id: 1,
      name: "Muller",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 7630,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "Thomas",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 2130,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
    },
  ],
  2: [
    {
      id: 1,
      name: "Schmickel",
      status: "Régulier",
      date_per: "2021-01-11",
      montant_rec: 2460,
      Hreg: 12,
      Hsup: 20,
      Treg: 25,
      Tsup: 33,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
    },
    {
      id: 2,
      name: "Shrek",
      status: "Occasionnel",
      date_per: "2021-01-11",
      montant_rec: 9830,
      Hreg: 86,
      Hsup: 41,
      Treg: 10,
      Tsup: 12,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const listeSal = {
  1: {
    name: "Oussama",
    taux_vac: 0.25,
  },
  2: {
    name: "Hicham",
    taux_vac: 0.3,
  },
};
