export const salairesAll = {
  0: [],
  1: [
    {
      id: 1,
      name: "Aimarah Oussama",
      status: "occ",
      date_per: "2021-02-11",
      montant_rec: 2460,
      Hreg: 12,
      Hsup: 20,
      Hsup2: 12,
      Treg: 25,
      Tsup: 33,
      Tsup2: 20,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
      type: "dab",
      site_con: "Site 16",
    },
    {
      id: 2,
      name: "Karim",
      status: "reg",
      date_per: "2021-04-30",
      montant_rec: 9830,
      Hreg: 86,
      Hsup: 41,
      Hsup2: 12,
      Treg: 10,
      Tsup: 12,
      Tsup2: 20,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: false,
      fss: true,
      csst: false,
      type: "bcg",
      site_con: "Site 1",
    },
  ],
  2: [
    {
      id: 1,
      name: "Said 2",
      status: "reg",
      date_per: "2021-12-11",
      montant_rec: 2460,
      Hreg: 12,
      Hsup: 20,
      Hsup2: 12,
      Treg: 25,
      Tsup: 33,
      Tsup2: 20,
      taux_vac: 0.25,
      ae: true,
      rrq: false,
      rqap: true,
      fss: true,
      csst: false,
      type: "mi",
    },
    {
      id: 2,
      name: "Karim 2",
      status: "occ",
      date_per: "2021-01-01",
      montant_rec: 9830,
      Hreg: 86,
      Hsup: 41,
      Hsup2: 12,
      Treg: 10,
      Tsup: 12,
      Tsup2: 20,
      taux_vac: 0.25,
      ae: true,
      rrq: true,
      rqap: true,
      fss: true,
      csst: false,
      type: "mpt",
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
};

export const listeSal = {
  1: {
    name: "Oussama",
    taux_vac: 0.25,
  },
  2: {
    name: "Hicham",
    taux_vac: 0.3,
  },
};
